###########
# site.url, site.title

title: 'RAML'

## note: 
#  use site.path in your templates to make it work for both protocols e.g. http and https
#  use site.url only inside the web feed template (e.g. requires full url incl. protocol)
path:
baseurl:
url: ""
permalink: "/blogs/:title"
timezone:      null

########
# more settings

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded



exclude:
- README.md


safe: true
lsi: false

# Where things are
source:      .
destination: ./_site
layouts_dir:     ./_layouts
data_dir: ./_data
# collections: null

# Handling Reading
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from

defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts

collections:
    testimonials:
        output: true

projectsgithuburl: https://github.com/raml-org/raml-org/tree/develop